<!doctype html>
<html lang="ru">
  <head>

    <title><?php echo $this->title; ?></title>
    
    <!-- META -->
    
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <meta name="description" content="<?php echo $this->description; ?>">
    <meta name="keywords" content="<?php echo $this->keywords; ?>">

    <!-- ICONS -->
    
    <link rel="shortcut icon" href="./favicon.ico?v=1.0" type="image/x-icon">

    <!-- STYLES -->
    
    <!-- Latest compiled and minified CSS Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"  media="all">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"  media="all">
    <link type="text/css" rel="stylesheet" href="<?php echo Constants::url()->DIR_CSS; ?>framework.css"  media="all">
    
    <!-- SCRIPTS -->
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries. WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Latest JQUERY -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <!-- Latest compiled and minified JavaScript Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <script type="text/javascript" charset="utf-8" src="<?php echo Constants::url()->DIR_JS; ?>core.js"></script>
    <script type="text/javascript" charset="utf-8" src="<?php echo Constants::url()->DIR_JS; ?>ajax.js"></script>
    <script type="text/javascript" charset="utf-8" src="<?php echo Constants::url()->DIR_JS; ?>route.js"></script>
    <script type="text/javascript" charset="utf-8" src="<?php echo Constants::url()->DIR_JS; ?>framework.js"></script>
    
    <?php echo ($this->debug->init()); ?>
  </head>
  <body>
      <?php echo $this->content; ?>
  </body>
</html>